# Generated by Django 5.0.3 on 2024-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StarWarsCharactersFileMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=64, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
